# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Design Theme
LUCI_DEPENDS:=
PKG_VERSION:=7.1
PKG_RELEASE:=20260411

LUCI_MINIFY_CSS:=
CONFIG_LUCI_CSSTIDY:=

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
