#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=50
USE_PROCD=1

start_service() {

	config_load "xupnpd"
	
	local enabled
	config_get_bool enabled config enabled 0
	
	[ "${enabled}" -gt 0 ] || return
	
	procd_open_instance
	procd_set_param command /usr/bin/xupnpd
	procd_append_param command -d /usr/share/xupnpd
	procd_set_param respawn
	procd_close_instance
}
