include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for the PHTunnel
LUCI_DEPENDS:=+cgi-io +curl +luci-compat +luci-lib-json +phtunnel

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
