#!/bin/sh

uci -q batch <<-EOF >/dev/null
        delete ucitrack.@ttyd[-1]
        add ucitrack ttyd
        set ucitrack.@ttyd[-1].init=ttyd
        commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
