include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-minieap
PKG_VERSION=1.0
PKG_RELEASE:=1

LUCI_TITLE:=minieap 802.1X Client for LuCI
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+minieap

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
