#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh -c 'while :; do /usr/bin/ucode /usr/libexec/luci-client-history; sleep 10; done'
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}
