#
# Copyright (C) 2019 Jo-Philipp Wich <jo@mein.io>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-compat

LUCI_TYPE:=mod
LUCI_BASENAME:=compat

LUCI_TITLE:=LuCI compatibility libraries

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature