#
# Copyright (C) 2022 Lean
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI page for XUPNPD
LUCI_DEPENDS:=+xupnpd
PKG_VERSION:=1
PKG_RELEASE:=9

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature


