#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=50
USE_PROCD=1
MAIN_CFG=config

capture_main_cfg() {
	[ -n "$MAIN_CFG" ] || MAIN_CFG="$1"
}

find_main_cfg() {
	local marker

	MAIN_CFG=config
	config_get marker "$MAIN_CFG" "enabled"
	[ -n "$marker" ] && return 0

	MAIN_CFG=
	config_foreach capture_main_cfg "eqos"
	[ -n "$MAIN_CFG" ] || MAIN_CFG=config
}

parse_device() {
	local cfg="$1"

	local enabled
	config_get_bool enabled "$cfg" "enabled" "1"
	[ "$enabled" -eq "1" ] || return 1

	local ip download upload
	config_get ip "$cfg" "ip"
	config_get download "$cfg" "download"
	config_get upload "$cfg" "upload"

	eqos add "$ip" "$download" "$upload"
}

start_service() {
	config_load "eqos"
	find_main_cfg

	local enabled
	config_get_bool enabled "$MAIN_CFG" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 1

	local mode download upload nss_interface nss_qdisc_opts
	config_get mode "$MAIN_CFG" "mode" "software"
	config_get download "$MAIN_CFG" "download"
	config_get upload "$MAIN_CFG" "upload"
	config_get nss_interface "$MAIN_CFG" "nss_interface"
	config_get nss_qdisc_opts "$MAIN_CFG" "nss_qdisc_opts"

	eqos start "$mode" "$download" "$upload" "$nss_interface" "$nss_qdisc_opts" || return 1

	[ "$mode" = "software" ] && config_foreach parse_device "device"
}

stop_service() {
	eqos stop
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "eqos"
}
