#
# Copyright 2022-2024 Rafał Wabik - IceG - From eko.one.pl forum
#
# MIT License
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI JS Support for modemband application
LUCI_DESCRIPTION:=LuCI JS interface for the modemband. The package allows set LTE/5G bands for selected 4G/5G modems.
LUCI_DEPENDS:=+modemband

PKG_NAME:=luci-app-modemband
PKG_VERSION:=1.0.25.20240519
PKG_MAINTAINER:=Rafał Wabik <4Rafal@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
