# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2025 ImmortalWrt.org

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for SYSU H3C 802.1X Client
LUCI_DEPENDS:=+sysuh3c

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
