# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Netgear Theme
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_RELEASE:=3

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
