#!/bin/sh

if [ -f /etc/init.d/zerotier -a -f /etc/init.d/luci-zerotier -a ! -f /etc/init.d/net-zerotier ]; then
	mv /etc/init.d/zerotier /etc/init.d/net-zerotier
	cp /etc/init.d/luci-zerotier /etc/init.d/zerotier
fi
exit 0
